/*
 * Copyright 2013-2025 the original author or authors from the JHipster project.
 *
 * This file is part of the JHipster project, see https://www.jhipster.tech/
 * for more information.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.jhipster.generator.domain.templates;

import io.github.jhipster.generator.domain.model.EntityContext;
import io.github.jhipster.generator.domain.model.FieldContext;
import io.github.jhipster.generator.domain.model.RelationshipContext;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates assertion helper class for an entity.
 * This is the Java equivalent of _persistClass_Asserts.java.ejs template.
 */
public class EntityAssertsGenerator {

    private final EntityContext context;
    private final StringBuilder sb;
    private int indentLevel = 0;
    private static final String INDENT = "    ";

    public EntityAssertsGenerator(EntityContext context) {
        this.context = context;
        this.sb = new StringBuilder();
    }

    /**
     * Generates the complete asserts class source code.
     *
     * @return the generated Java source code
     */
    public String generate() {
        sb.setLength(0);

        generatePackageDeclaration();
        generateImports();
        generateClassDeclaration();
        generateAllPropertiesEqualsMethod();
        generateAllUpdatablePropertiesEqualsMethod();
        generateMapsIdRelationshipMethod();
        generateAutoGeneratedPropertiesEqualsMethod();
        generateUpdatableFieldsEqualsMethod();
        generateUpdatableRelationshipsEqualsMethod();
        generateClassClose();

        return sb.toString();
    }

    private void generatePackageDeclaration() {
        appendLine("package " + context.getEntityAbsolutePackage() + ".domain;");
        appendLine();
    }

    private void generateImports() {
        appendLine("import static org.junit.jupiter.api.Assertions.assertAll;");
        appendLine("import static org.assertj.core.api.Assertions.assertThat;");
        appendLine();

        if (context.isAnyFieldIsBigDecimal()) {
            appendLine("import static " + context.getPackageName() + ".domain.AssertUtils.bigDecimalCompareTo;");
        }
        if (context.isAnyFieldIsZonedDateTime()) {
            appendLine("import static " + context.getPackageName() + ".domain.AssertUtils.zonedDataTimeSameInstant;");
        }

        appendLine();
    }

    private void generateClassDeclaration() {
        appendLine("public class " + context.getPersistClass() + "Asserts {");
        appendLine();
        indentLevel++;
    }

    private void generateAllPropertiesEqualsMethod() {
        String persistClass = context.getPersistClass();

        appendLine("/**");
        appendLine(" * Asserts that the entity has all properties (fields/relationships) set.");
        appendLine(" *");
        appendLine(" * @param expected the expected entity");
        appendLine(" * @param actual the actual entity");
        appendLine(" */");
        appendLine("public static void assert" + persistClass + "AllPropertiesEquals(" + persistClass + " expected, " + persistClass + " actual) {");
        indentLevel++;
        appendLine("assert" + persistClass + "AutoGeneratedPropertiesEquals(expected, actual);");
        appendLine("assert" + persistClass + "AllUpdatablePropertiesEquals(expected, actual);");
        indentLevel--;
        appendLine("}");
        appendLine();
    }

    private void generateAllUpdatablePropertiesEqualsMethod() {
        String persistClass = context.getPersistClass();

        appendLine("/**");
        appendLine(" * Asserts that the entity has all updatable properties (fields/relationships) set.");
        appendLine(" *");
        appendLine(" * @param expected the expected entity");
        appendLine(" * @param actual the actual entity");
        appendLine(" */");
        appendLine("public static void assert" + persistClass + "AllUpdatablePropertiesEquals(" + persistClass + " expected, " + persistClass + " actual) {");
        indentLevel++;
        appendLine("assert" + persistClass + "UpdatableFieldsEquals(expected, actual);");
        appendLine("assert" + persistClass + "UpdatableRelationshipsEquals(expected, actual);");
        indentLevel--;
        appendLine("}");
    }

    private void generateMapsIdRelationshipMethod() {
        if (context.isEmbedded() || context.getPrimaryKey() == null || !context.getPrimaryKey().isComposite()) {
            return;
        }

        // For MapsId/derived primary keys - simplified version
        appendLine();
        String persistClass = context.getPersistClass();

        appendLine("/**");
        appendLine(" * Asserts that the derived primary key is set correctly.");
        appendLine(" *");
        appendLine(" * @param entityToPersist the entity used to persist");
        appendLine(" * @param persisted the persisted entity");
        appendLine(" */");
        appendLine("public static void assert" + persistClass + "MapsIdRelationshipPersistedValue(" + persistClass + " entityToPersist, " + persistClass + " persisted) {");
        indentLevel++;
        appendLine("// Validate the id for MapsId, the ids must be same");
        appendLine("// Implementation depends on specific primary key configuration");
        indentLevel--;
        appendLine("}");
    }

    private void generateAutoGeneratedPropertiesEqualsMethod() {
        appendLine();
        String persistClass = context.getPersistClass();

        appendLine("/**");
        appendLine(" * Asserts that the entity has all the auto generated properties (fields/relationships) set.");
        appendLine(" *");
        appendLine(" * @param expected the expected entity");
        appendLine(" * @param actual the actual entity");
        appendLine(" */");
        appendLine("public static void assert" + persistClass + "AutoGeneratedPropertiesEquals(" + persistClass + " expected, " + persistClass + " actual) {");
        indentLevel++;

        List<FieldContext> autoGeneratedFields = getAutoGeneratedFields();

        if (autoGeneratedFields.isEmpty()) {
            appendLine("// empty method");
        } else {
            appendLine("assertThat(actual)");
            indentLevel++;
            appendLine(".as(\"Verify " + persistClass + " auto generated properties\")");
            for (FieldContext field : autoGeneratedFields) {
                appendLine(".satisfies(a -> assertThat(a.get" + field.getFieldInJavaBeanMethod() + "()).as(\"check " + field.getPropertyName() + "\").isEqualTo(expected.get" + field.getFieldInJavaBeanMethod() + "()))");
            }
            sb.setLength(sb.length() - 1); // Remove last newline
            sb.append(";\n");
            indentLevel--;
        }

        indentLevel--;
        appendLine("}");
    }

    private void generateUpdatableFieldsEqualsMethod() {
        appendLine();
        String persistClass = context.getPersistClass();

        appendLine("/**");
        appendLine(" * Asserts that the entity has all the updatable fields set.");
        appendLine(" *");
        appendLine(" * @param expected the expected entity");
        appendLine(" * @param actual the actual entity");
        appendLine(" */");
        appendLine("public static void assert" + persistClass + "UpdatableFieldsEquals(" + persistClass + " expected, " + persistClass + " actual) {");
        indentLevel++;

        List<FieldContext> updatableFields = getUpdatableFields();

        if (updatableFields.isEmpty()) {
            appendLine("// empty method");
        } else {
            appendLine("assertThat(actual)");
            indentLevel++;
            appendLine(".as(\"Verify " + persistClass + " relevant properties\")");
            for (FieldContext field : updatableFields) {
                String comparator = getFieldComparator(field);
                if (comparator != null) {
                    appendLine(".satisfies(a -> assertThat(a.get" + field.getFieldInJavaBeanMethod() + "()).as(\"check " + field.getPropertyName() + "\").usingComparator(" + comparator + ").isEqualTo(expected.get" + field.getFieldInJavaBeanMethod() + "()))");
                } else {
                    appendLine(".satisfies(a -> assertThat(a.get" + field.getFieldInJavaBeanMethod() + "()).as(\"check " + field.getPropertyName() + "\").isEqualTo(expected.get" + field.getFieldInJavaBeanMethod() + "()))");
                    if (field.isFieldWithContentType()) {
                        appendLine(".satisfies(a -> assertThat(a.get" + field.getFieldInJavaBeanMethod() + "ContentType()).as(\"check " + field.getPropertyName() + " content type\").isEqualTo(expected.get" + field.getFieldInJavaBeanMethod() + "ContentType()))");
                    }
                }
            }
            sb.setLength(sb.length() - 1); // Remove last newline
            sb.append(";\n");
            indentLevel--;
        }

        appendLine();
        indentLevel--;
        appendLine("}");
    }

    private void generateUpdatableRelationshipsEqualsMethod() {
        appendLine();
        String persistClass = context.getPersistClass();

        appendLine("/**");
        appendLine(" * Asserts that the entity has all the updatable relationships set.");
        appendLine(" *");
        appendLine(" * @param expected the expected entity");
        appendLine(" * @param actual the actual entity");
        appendLine(" */");
        appendLine("public static void assert" + persistClass + "UpdatableRelationshipsEquals(" + persistClass + " expected, " + persistClass + " actual) {");
        indentLevel++;

        List<RelationshipContext> updatableRelationships = getUpdatableRelationships();

        if (updatableRelationships.isEmpty()) {
            appendLine("// empty method");
        } else {
            appendLine("assertThat(actual)");
            indentLevel++;
            appendLine(".as(\"Verify " + persistClass + " relationships\")");
            for (RelationshipContext rel : updatableRelationships) {
                appendLine(".satisfies(a -> assertThat(a.get" + rel.getPropertyJavaBeanName() + "()).as(\"check " + rel.getPropertyName() + "\").isEqualTo(expected.get" + rel.getPropertyJavaBeanName() + "()))");
            }
            sb.setLength(sb.length() - 1); // Remove last newline
            sb.append(";\n");
            indentLevel--;
        }

        indentLevel--;
        appendLine("}");
    }

    private void generateClassClose() {
        indentLevel--;
        appendLine("}");
    }

    // Helper methods

    private List<FieldContext> getAutoGeneratedFields() {
        return context.getFields().stream()
            .filter(f -> !f.isTransientField() && f.isId()) // Typically ID is auto-generated
            .collect(Collectors.toList());
    }

    private List<FieldContext> getUpdatableFields() {
        return context.getFields().stream()
            .filter(f -> !f.isTransientField() && !f.isId())
            .collect(Collectors.toList());
    }

    private List<RelationshipContext> getUpdatableRelationships() {
        return context.getRelationships().stream()
            .filter(rel -> {
                EntityContext otherEntity = rel.getOtherEntity();
                if (context.isEmbedded() && otherEntity != null && !otherEntity.isEmbedded()) {
                    return false;
                }
                // Filter out built-in user relationships
                return otherEntity == null || !otherEntity.isBuiltInUser();
            })
            .collect(Collectors.toList());
    }

    private String getFieldComparator(FieldContext field) {
        if ("ZonedDateTime".equals(field.getJavaFieldType())) {
            return "zonedDataTimeSameInstant";
        } else if ("BigDecimal".equals(field.getJavaFieldType())) {
            return "bigDecimalCompareTo";
        }
        return null;
    }

    private void appendLine() {
        sb.append("\n");
    }

    private void appendLine(String line) {
        sb.append(getIndent()).append(line).append("\n");
    }

    private String getIndent() {
        return INDENT.repeat(indentLevel);
    }
}
